version: '3'
services:
  app:
    container_name: codigniter4
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
      - ./writable:/var/www/html/writable
    depends_on:
      - db
    ports:
      - 8080:80

  db:
    container_name: codigniter4-db
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Demo_12345
      MYSQL_DATABASE: ci_docker
      MYSQL_USER: user
      MYSQL_PASSWORD: Demo_12345
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
volumes:
  db_data: